"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ModelType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ModelTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ModelType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STANDARD: _ModelType.ValueType  # 0
    HYBRID: _ModelType.ValueType  # 1

class ModelType(_ModelType, metaclass=_ModelTypeEnumTypeWrapper): ...

STANDARD: ModelType.ValueType  # 0
HYBRID: ModelType.ValueType  # 1
global___ModelType = ModelType

class _HeadingDirection:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HeadingDirectionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HeadingDirection.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESERVED: _HeadingDirection.ValueType  # 0
    STRAIGHT: _HeadingDirection.ValueType  # 1
    LEFT: _HeadingDirection.ValueType  # 2
    HARD_LEFT: _HeadingDirection.ValueType  # 3
    RIGHT: _HeadingDirection.ValueType  # 4
    HARD_RIGHT: _HeadingDirection.ValueType  # 5

class HeadingDirection(_HeadingDirection, metaclass=_HeadingDirectionEnumTypeWrapper): ...

RESERVED: HeadingDirection.ValueType  # 0
STRAIGHT: HeadingDirection.ValueType  # 1
LEFT: HeadingDirection.ValueType  # 2
HARD_LEFT: HeadingDirection.ValueType  # 3
RIGHT: HeadingDirection.ValueType  # 4
HARD_RIGHT: HeadingDirection.ValueType  # 5
global___HeadingDirection = HeadingDirection

@typing.final
class DroneState(google.protobuf.message.Message):
    """define drone state"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(
        self,
        *,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___DroneState = DroneState

@typing.final
class TrajectoryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    TARGET_STATE_FIELD_NUMBER: builtins.int
    DURATION_S_FIELD_NUMBER: builtins.int
    SAMPLING_TIME_FIELD_NUMBER: builtins.int
    MODEL_TYPE_FIELD_NUMBER: builtins.int
    NUM_WAYPOINTS_FIELD_NUMBER: builtins.int
    NOISE_FIELD_NUMBER: builtins.int
    duration_s: builtins.int
    sampling_time: builtins.float
    model_type: global___ModelType.ValueType
    num_waypoints: builtins.int
    noise: builtins.bool
    @property
    def state(self) -> global___DroneState: ...
    @property
    def target_state(self) -> global___DroneState: ...
    def __init__(
        self,
        *,
        state: global___DroneState | None = ...,
        target_state: global___DroneState | None = ...,
        duration_s: builtins.int = ...,
        sampling_time: builtins.float = ...,
        model_type: global___ModelType.ValueType = ...,
        num_waypoints: builtins.int = ...,
        noise: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["state", b"state", "target_state", b"target_state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["duration_s", b"duration_s", "model_type", b"model_type", "noise", b"noise", "num_waypoints", b"num_waypoints", "sampling_time", b"sampling_time", "state", b"state", "target_state", b"target_state"]) -> None: ...

global___TrajectoryRequest = TrajectoryRequest

@typing.final
class TrajectoryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAJECTORY_FIELD_NUMBER: builtins.int
    @property
    def trajectory(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DroneState]: ...
    def __init__(
        self,
        *,
        trajectory: collections.abc.Iterable[global___DroneState] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["trajectory", b"trajectory"]) -> None: ...

global___TrajectoryResponse = TrajectoryResponse

@typing.final
class DirectionRequest(google.protobuf.message.Message):
    """DEFINE DIRECTION REQUEST"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    MODEL_TYPE_FIELD_NUMBER: builtins.int
    model_type: global___ModelType.ValueType
    @property
    def state(self) -> global___DroneState: ...
    def __init__(
        self,
        *,
        state: global___DroneState | None = ...,
        model_type: global___ModelType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["state", b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["model_type", b"model_type", "state", b"state"]) -> None: ...

global___DirectionRequest = DirectionRequest

@typing.final
class DirectionResponse(google.protobuf.message.Message):
    """DEFINE DIRECTION RESPONSE"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISCRETE_HEADING_FIELD_NUMBER: builtins.int
    CONTINUOUS_HEADING_FIELD_NUMBER: builtins.int
    @property
    def discrete_heading(self) -> global___DiscreteHeading: ...
    @property
    def continuous_heading(self) -> global___ContinuousHeading: ...
    def __init__(
        self,
        *,
        discrete_heading: global___DiscreteHeading | None = ...,
        continuous_heading: global___ContinuousHeading | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["continuous_heading", b"continuous_heading", "control_type", b"control_type", "discrete_heading", b"discrete_heading"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["continuous_heading", b"continuous_heading", "control_type", b"control_type", "discrete_heading", b"discrete_heading"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["control_type", b"control_type"]) -> typing.Literal["discrete_heading", "continuous_heading"] | None: ...

global___DirectionResponse = DirectionResponse

@typing.final
class DiscreteHeading(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DIRECTION_FIELD_NUMBER: builtins.int
    direction: global___HeadingDirection.ValueType
    def __init__(
        self,
        *,
        direction: global___HeadingDirection.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["direction", b"direction"]) -> None: ...

global___DiscreteHeading = DiscreteHeading

@typing.final
class ContinuousHeading(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RAD_FIELD_NUMBER: builtins.int
    rad: builtins.float
    def __init__(
        self,
        *,
        rad: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["rad", b"rad"]) -> None: ...

global___ContinuousHeading = ContinuousHeading
