# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hyrl.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hyrl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhyrl.proto\x12\x04hyrl\"9\n\x10\x44irectionRequest\x12%\n\x0b\x64rone_state\x18\x01 \x01(\x0b\x32\x10.hyrl.DroneState\"-\n\nDroneState\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x8d\x01\n\x11\x44irectionResponse\x12\x31\n\x10\x64iscrete_heading\x18\x02 \x01(\x0b\x32\x15.hyrl.DiscreteHeadingH\x00\x12\x35\n\x12\x63ontinuous_heading\x18\x03 \x01(\x0b\x32\x17.hyrl.ContinuousHeadingH\x00\x42\x0e\n\x0c\x63ontrol_type\"<\n\x0f\x44iscreteHeading\x12)\n\tdirection\x18\x01 \x01(\x0e\x32\x16.hyrl.HeadingDirection\" \n\x11\x43ontinuousHeading\x12\x0b\n\x03rad\x18\x01 \x01(\x02\";\n\x15SetEnvironmentRequest\x12\"\n\tobstacles\x18\x01 \x03(\x0b\x32\x0f.hyrl.Polygon2D\"*\n\tPolygon2D\x12\x1d\n\x06points\x18\x01 \x03(\x0b\x32\r.hyrl.Point2D\"\x1f\n\x07Point2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\")\n\x16SetEnvironmentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t*T\n\x10HeadingDirection\x12\x0c\n\x08STRAIGHT\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\r\n\tHARD_LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03\x12\x0e\n\nHARD_RIGHT\x10\x04\x32\xa8\x01\n\x18ObstacleAvoidanceService\x12K\n\x0eSetEnvironment\x12\x1b.hyrl.SetEnvironmentRequest\x1a\x1c.hyrl.SetEnvironmentResponse\x12?\n\x0cGetDirection\x12\x16.hyrl.DirectionRequest\x1a\x17.hyrl.DirectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hyrl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADINGDIRECTION']._serialized_start=547
  _globals['_HEADINGDIRECTION']._serialized_end=631
  _globals['_DIRECTIONREQUEST']._serialized_start=20
  _globals['_DIRECTIONREQUEST']._serialized_end=77
  _globals['_DRONESTATE']._serialized_start=79
  _globals['_DRONESTATE']._serialized_end=124
  _globals['_DIRECTIONRESPONSE']._serialized_start=127
  _globals['_DIRECTIONRESPONSE']._serialized_end=268
  _globals['_DISCRETEHEADING']._serialized_start=270
  _globals['_DISCRETEHEADING']._serialized_end=330
  _globals['_CONTINUOUSHEADING']._serialized_start=332
  _globals['_CONTINUOUSHEADING']._serialized_end=364
  _globals['_SETENVIRONMENTREQUEST']._serialized_start=366
  _globals['_SETENVIRONMENTREQUEST']._serialized_end=425
  _globals['_POLYGON2D']._serialized_start=427
  _globals['_POLYGON2D']._serialized_end=469
  _globals['_POINT2D']._serialized_start=471
  _globals['_POINT2D']._serialized_end=502
  _globals['_SETENVIRONMENTRESPONSE']._serialized_start=504
  _globals['_SETENVIRONMENTRESPONSE']._serialized_end=545
  _globals['_OBSTACLEAVOIDANCESERVICE']._serialized_start=634
  _globals['_OBSTACLEAVOIDANCESERVICE']._serialized_end=802
# @@protoc_insertion_point(module_scope)
