# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: hyrl.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import hyrl_pb2


class ObstacleAvoidanceServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SetEnvironment(self, stream: 'grpclib.server.Stream[hyrl_pb2.SetEnvironmentRequest, hyrl_pb2.SetEnvironmentResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetDirection(self, stream: 'grpclib.server.Stream[hyrl_pb2.DirectionRequest, hyrl_pb2.DirectionResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/hyrl.ObstacleAvoidanceService/SetEnvironment': grpclib.const.Handler(
                self.SetEnvironment,
                grpclib.const.Cardinality.UNARY_UNARY,
                hyrl_pb2.SetEnvironmentRequest,
                hyrl_pb2.SetEnvironmentResponse,
            ),
            '/hyrl.ObstacleAvoidanceService/GetDirection': grpclib.const.Handler(
                self.GetDirection,
                grpclib.const.Cardinality.UNARY_UNARY,
                hyrl_pb2.DirectionRequest,
                hyrl_pb2.DirectionResponse,
            ),
        }


class ObstacleAvoidanceServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SetEnvironment = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hyrl.ObstacleAvoidanceService/SetEnvironment',
            hyrl_pb2.SetEnvironmentRequest,
            hyrl_pb2.SetEnvironmentResponse,
        )
        self.GetDirection = grpclib.client.UnaryUnaryMethod(
            channel,
            '/hyrl.ObstacleAvoidanceService/GetDirection',
            hyrl_pb2.DirectionRequest,
            hyrl_pb2.DirectionResponse,
        )
